# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/', priorities: ['json', 'xml'], fallback_format: 'json', prefer_extension: true }
    versioning: true
    view:
        formats:
            xml:  true
            json: true
        view_response_listener: 'force'
    zone:
        - { path: ^/api/* }

    serializer:
        # version:              null
        groups:               ~

    # service:
    #     serializer:           'fos_rest.serializer.jms'
