itk_dev_user:
    site_name: '%env(SITE_NAME)%'
    site_url: '%env(SITE_URL)%'

    sender:
        email: '%env(MAILER_FROM_EMAIL)%'
        name: '%env(MAILER_FROM_NAME)%'

    # Template for mails sent to new users
    user_created:
        subject: '%user_created_user_subject%'
        header: '%user_created_user_header%'
        body: '%user_created_user_body%'
        button:
            text: '%user_created_user_button_text%'
        footer: '%user_created_user_footer%'

    # Set to true to automatically notify users on creation.
    notify_user_on_create: false
